//! The pool universe: which accounts to watch, and what the mints in them are.
//!
//! Generated by `scripts/build_registry.py` and embedded at compile time. Embedding
//! rather than reading a file at start-up is deliberate — the pool set is part of
//! what an experiment *was*, so a measurement written to the ledger can always be
//! traced back to the exact universe that produced it, by way of the commit.
//!
//! Nothing in here is authoritative about money. Symbols and decimals are for display
//! and USD conversion; `fee_ppm` and `tvl_usd` are for ordering. Every fee and every
//! reserve used in a quote is decoded from the chain at run time.

use anyhow::{Context, Result};
use cb_core::types::{Dex, Pubkey32};
use serde::Deserialize;
use std::collections::HashMap;

/// The generated registry, as it appears on disk.
const EMBEDDED: &str = include_str!("../pools.json");

#[derive(Debug, Clone, Deserialize)]
struct RawRegistry {
    base_mints: Vec<String>,
    mints: HashMap<String, RawMint>,
    pools: Vec<RawPool>,
}

#[derive(Debug, Clone, Deserialize)]
struct RawMint {
    symbol: String,
    decimals: u8,
}

#[derive(Debug, Clone, Deserialize)]
struct RawPool {
    address: String,
    dex: String,
    label: String,
    mint_a: String,
    mint_b: String,
    fee_ppm: u32,
    tvl_usd: f64,
}

#[derive(Debug, Clone, PartialEq, Eq)]
pub struct MintInfo {
    pub symbol: String,
    pub decimals: u8,
}

#[derive(Debug, Clone)]
pub struct PoolEntry {
    pub address: Pubkey32,
    pub dex: Dex,
    pub label: String,
    pub mint_a: Pubkey32,
    pub mint_b: Pubkey32,
    /// What the venue's directory said the fee was when the registry was generated.
    /// Never used to price anything — the live value comes from the chain.
    pub fee_ppm_hint: u32,
    pub tvl_usd: f64,
}

#[derive(Debug, Clone)]
pub struct Registry {
    /// Mints a cycle may start and end in, because we can hold them.
    pub base_mints: Vec<Pubkey32>,
    pub mints: HashMap<Pubkey32, MintInfo>,
    pub pools: Vec<PoolEntry>,
}

/// Base58-decode a 32-byte public key.
pub fn pk(s: &str) -> Result<Pubkey32> {
    let v = bs58::decode(s).into_vec().with_context(|| format!("bad base58: {s}"))?;
    v.as_slice().try_into().with_context(|| format!("not 32 bytes: {s}"))
}

fn parse_dex(s: &str) -> Result<Dex> {
    Ok(match s {
        "orca_whirlpool" => Dex::OrcaWhirlpool,
        "raydium_clmm" => Dex::RaydiumClmm,
        "raydium_v4" => Dex::RaydiumAmmV4,
        "raydium_cpmm" => Dex::RaydiumCpmm,
        "meteora_damm_v2" => Dex::MeteoraDammV2,
        "pumpswap" => Dex::PumpSwap,
        other => anyhow::bail!("unknown dex {other:?} in registry"),
    })
}

impl Registry {
    /// Parse the embedded registry.
    pub fn embedded() -> Result<Self> {
        Self::parse(EMBEDDED)
    }

    pub fn parse(json: &str) -> Result<Self> {
        let raw: RawRegistry = serde_json::from_str(json).context("registry is not valid json")?;

        let mut mints = HashMap::with_capacity(raw.mints.len());
        for (addr, m) in raw.mints {
            mints.insert(pk(&addr)?, MintInfo { symbol: m.symbol, decimals: m.decimals });
        }

        let mut pools = Vec::with_capacity(raw.pools.len());
        for p in raw.pools {
            let (mint_a, mint_b) = (pk(&p.mint_a)?, pk(&p.mint_b)?);
            // Derive the label from the mints rather than trusting the upstream string.
            //
            // Two sources name wrapped SOL differently, so the *same* mint pair arrived
            // as both "SOL/USDC" and "WSOL/USDC" — ten pools on one pair rendering as
            // two unrelated ones. Nothing routes on the label, so this never affected a
            // price; it affected every human reading of the universe, including the
            // count of how many venues quote a pair, which is the whole basis for
            // deciding a pair is worth watching. Unknown mints keep the upstream label,
            // since an address prefix is a worse name than a hand-written one.
            let label = match (mints.get(&mint_a), mints.get(&mint_b)) {
                (Some(a), Some(b)) => format!("{}/{}", a.symbol, b.symbol),
                _ => p.label,
            };
            pools.push(PoolEntry {
                address: pk(&p.address)?,
                dex: parse_dex(&p.dex)?,
                label,
                mint_a,
                mint_b,
                fee_ppm_hint: p.fee_ppm,
                tvl_usd: p.tvl_usd,
            });
        }

        let base_mints = raw.base_mints.iter().map(|s| pk(s)).collect::<Result<Vec<_>>>()?;

        anyhow::ensure!(!pools.is_empty(), "registry has no pools");
        anyhow::ensure!(!base_mints.is_empty(), "registry has no base mints");
        Ok(Self { base_mints, mints, pools })
    }

    /// Display symbol for a mint. Unknown mints degrade to an address prefix rather
    /// than a guess — routing never reads this, so a wrong label is cosmetic, but a
    /// label that *looks* authoritative when it is not is worse than an obvious stub.
    #[must_use]
    pub fn symbol(&self, mint: &Pubkey32) -> String {
        self.mints.get(mint).map_or_else(
            || bs58::encode(mint).into_string().chars().take(4).collect(),
            |m| m.symbol.clone(),
        )
    }

    /// Decimals for a mint, defaulting to 9 (SOL's) when unknown.
    #[must_use]
    pub fn decimals(&self, mint: &Pubkey32) -> u8 {
        self.mints.get(mint).map_or(9, |m| m.decimals)
    }

    /// How many WebSocket subscriptions this universe needs.
    ///
    /// Concentrated pools cost one; Raydium AMM v4 costs three, because its reserves
    /// live in two separate vault accounts that must be watched alongside the pool.
    #[must_use]
    pub fn subscription_estimate(&self) -> usize {
        self.pools.iter().map(|p| if p.dex.is_self_contained() { 1 } else { 3 }).sum()
    }

    /// Pools grouped by the unordered mint pair they quote.
    ///
    /// A pair with more than one entry is a **direct round trip**: buy on one venue,
    /// sell on the other, two hops, no third token involved. Those are the cheapest
    /// loops in the graph and the reason a multi-venue universe is worth the trouble.
    #[must_use]
    pub fn duplicate_pairs(&self) -> Vec<(String, Vec<&PoolEntry>)> {
        let mut by_pair: HashMap<(Pubkey32, Pubkey32), Vec<&PoolEntry>> = HashMap::new();
        for p in &self.pools {
            let key = if p.mint_a <= p.mint_b { (p.mint_a, p.mint_b) } else { (p.mint_b, p.mint_a) };
            by_pair.entry(key).or_default().push(p);
        }
        let mut out: Vec<(String, Vec<&PoolEntry>)> = by_pair
            .into_iter()
            .filter(|(_, v)| v.len() > 1)
            .map(|((a, b), v)| (format!("{}/{}", self.symbol(&a), self.symbol(&b)), v))
            .collect();
        out.sort_by(|a, b| b.1.len().cmp(&a.1.len()).then_with(|| a.0.cmp(&b.0)));
        out
    }

    /// Cheapest round trip available on each duplicated pair, in bps.
    ///
    /// This is the fee wall a two-hop cycle on that pair has to clear, using the
    /// directory's fee hints. Reported at start-up so the run's headline constraint is
    /// visible before any data arrives.
    #[must_use]
    pub fn cheapest_round_trips(&self) -> Vec<(String, f64)> {
        let mut out: Vec<(String, f64)> = self
            .duplicate_pairs()
            .into_iter()
            .filter_map(|(pair, mut pools)| {
                pools.sort_by_key(|p| p.fee_ppm_hint);
                let (a, b) = (pools.first()?, pools.get(1)?);
                let kept = (1.0 - f64::from(a.fee_ppm_hint) / 1e6)
                    * (1.0 - f64::from(b.fee_ppm_hint) / 1e6);
                Some((pair, (1.0 - kept) * 10_000.0))
            })
            .collect();
        out.sort_by(|a, b| a.1.total_cmp(&b.1));
        out
    }
}

#[cfg(test)]
mod tests {
    use super::*;

    /// The registry that actually ships must parse, or the binary cannot start.
    #[test]
    fn the_embedded_registry_parses() {
        let r = Registry::embedded().expect("embedded registry must parse");
        assert!(r.pools.len() >= 20, "expected a real universe, got {}", r.pools.len());
        assert!(r.mints.len() >= 5);
        assert!(!r.base_mints.is_empty());
    }

    #[test]
    fn every_pool_references_mints_the_registry_knows() {
        let r = Registry::embedded().unwrap();
        for p in &r.pools {
            assert!(r.mints.contains_key(&p.mint_a), "{} mint_a unknown", p.label);
            assert!(r.mints.contains_key(&p.mint_b), "{} mint_b unknown", p.label);
            assert_ne!(p.mint_a, p.mint_b, "{} is a degenerate pair", p.label);
        }
    }

    #[test]
    fn base_mints_are_all_present_in_the_pool_graph() {
        let r = Registry::embedded().unwrap();
        for base in &r.base_mints {
            let n = r.pools.iter().filter(|p| p.mint_a == *base || p.mint_b == *base).count();
            assert!(n > 0, "base mint {} appears in no pool", r.symbol(base));
        }
    }

    /// Every mint must be reachable by at least two pools, or it can never be an
    /// intermediate hop and its pools are dead weight on the subscription budget.
    #[test]
    fn no_mint_is_a_dead_end() {
        let r = Registry::embedded().unwrap();
        let mut degree: HashMap<Pubkey32, usize> = HashMap::new();
        for p in &r.pools {
            *degree.entry(p.mint_a).or_default() += 1;
            *degree.entry(p.mint_b).or_default() += 1;
        }
        for (mint, n) in degree {
            assert!(n >= 2, "{} appears in only {n} pool — cannot be part of a cycle", r.symbol(&mint));
        }
    }

    /// The whole point of a multi-venue universe: some pair must be quoted twice, or
    /// the cheapest possible loop is still a three-hop triangle.
    #[test]
    fn some_pairs_are_quoted_by_more_than_one_venue() {
        let r = Registry::embedded().unwrap();
        let dupes = r.duplicate_pairs();
        assert!(!dupes.is_empty(), "no pair has two venues — no direct round trips exist");

        let cheapest = r.cheapest_round_trips();
        let (pair, bps) = &cheapest[0];
        assert!(
            *bps < 25.0,
            "the cheapest round trip is {pair} at {bps}bps, no better than a single \
             Raydium v4 swap — the low-fee venues are not actually in the universe"
        );
    }

    #[test]
    fn subscription_estimate_charges_vault_backed_pools_for_their_vaults() {
        let r = Registry::embedded().unwrap();
        let inline = r.pools.iter().filter(|p| p.dex.is_self_contained()).count();
        let vaulted = r.pools.len() - inline;
        assert_eq!(r.subscription_estimate(), inline + 3 * vaulted);
    }

    /// Raydium runs four AMM programs, three of which its API labels "Standard". They
    /// share no account layout, and the stable-swap one is long enough to pass a
    /// constant-product length check — so it would decode to plausible nonsense rather
    /// than failing. Nothing in the registry may claim to be a venue we cannot decode.
    #[test]
    fn every_pool_names_a_venue_we_have_a_decoder_for() {
        let r = Registry::embedded().unwrap();
        for p in &r.pools {
            assert!(
                matches!(
                    p.dex,
                    Dex::OrcaWhirlpool
                        | Dex::RaydiumClmm
                        | Dex::RaydiumAmmV4
                        | Dex::RaydiumCpmm
                        | Dex::MeteoraDammV2
                ),
                "{} claims venue {:?}, which has no live decoder",
                p.label,
                p.dex
            );
        }
    }

    #[test]
    fn unknown_mints_get_a_stub_symbol_not_a_guess() {
        let r = Registry::embedded().unwrap();
        assert_eq!(r.symbol(&[7u8; 32]).len(), 4);
        assert_eq!(r.decimals(&[7u8; 32]), 9);
    }

    #[test]
    fn malformed_registries_are_rejected() {
        assert!(Registry::parse("{}").is_err());
        assert!(Registry::parse(r#"{"base_mints":[],"mints":{},"pools":[]}"#).is_err());
        assert!(Registry::parse(
            r#"{"base_mints":["nope"],"mints":{},"pools":[
                {"address":"x","dex":"orca_whirlpool","label":"a/b","mint_a":"y",
                 "mint_b":"z","fee_ppm":100,"tvl_usd":1.0}]}"#
        )
        .is_err());
    }
}
