[package]
name = "cb-executor"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
cb-core = { workspace = true }
cb-wallet = { workspace = true }
anyhow = { workspace = true }
thiserror = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
solana-sdk = { workspace = true }
bincode = { workspace = true }
cb-dex = { workspace = true }
reqwest = { workspace = true }
bs58 = { workspace = true }
tracing = { workspace = true }
tokio = { workspace = true }
