[package]
name = "cb-bot"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
cb-core = { workspace = true }
cb-server = { workspace = true }
cb-scanner = { workspace = true }
cb-ledger = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
