[package]
name = "cb-bot"
version.workspace = true
edition.workspace = true
license.workspace = true
rust-version.workspace = true

[dependencies]
cb-core = { workspace = true }
cb-server = { workspace = true }
cb-scanner = { workspace = true }
cb-ledger = { workspace = true }
anyhow = { workspace = true }
tokio = { workspace = true }
tracing = { workspace = true }
tracing-subscriber = { workspace = true }
cb-dex = { workspace = true }
cb-executor = { workspace = true }
cb-wallet = { workspace = true }
solana-sdk = { workspace = true }
cb-feed = { workspace = true }
bs58 = { workspace = true }
reqwest = { workspace = true }
serde = { workspace = true }
serde_json = { workspace = true }
